apiVersion: apps/v1
kind: Deployment
metadata:
  name: shinyproxy
spec:
  selector:
    matchLabels:
      run: shinyproxy
  replicas: 1
  template:  
    metadata:
      labels:
        run: shinyproxy
    spec:
      containers:
      - name: shinyproxy
        image: shinyproxy-example
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
      - name: kube-proxy-sidecar
        image: kube-proxy-sidecar
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 5"] # wait 5 seconds to let shinyproxy remove the pods on graceful shutdown        
